version: 2.1

parameters:
  build-angular_fe:
    type: boolean
    default: false
  build-test:
    type:  boolean
    default: false

jobs:
  build-test-job:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: apps/test
      - run:
          command: jest
          working_directory: apps

      # - run: npm run test
      # - run: ../node_modules/.bin/jest
  build-angular-job:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run: echo 'Building angular'
      - run: cd apps/
      - run: npm i --production=false
      - run: npm run test-angular-fe

workflows:
  testbuildwf:
    when: << pipeline.parameters.build-test >>
    jobs:
      - build-test-job
  angularbuildwf:
    when: << pipeline.parameters.build-angular_fe >>
    jobs:
      - build-angular-job
