version: 2.1

parameters:
  build-angular_fe:
    type: boolean
    default: false
  build-test:
    type:  boolean
    default: false

jobs:
  build-test-job:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: echo 'Building Test'
      - run: node --version
      - run: cd apps/test
      - run: npm i --include=dev
      - run: jest
  build-angular-job:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: echo 'Building angular'
      - run: node --version
      - run: cd apps/angular-fe
      - run: npm i --include=dev
      - run: jest

workflows:
  testbuildwf:
    when: << pipeline.parameters.build-test >>
    jobs:
      - build-test-job
  angularbuildwf:
    when: << pipeline.parameters.build-angular_fe >>
    jobs:
      - build-angular-job
