version: 2.1

parameters:
  build-angular_fe:
    type: boolean
    default: false
  build-test:
    type:  boolean
    default: false
  build-alpha_be:
    type: boolean
    default: false

orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build-test-job:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run: npm install
      # must direct to the bin bc it won't run jest command direct
      - run: node_modules/.bin/jest

      # - run: npm run test
      # - run: ../node_modules/.bin/jest
  build-angular-job:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run: echo 'Building angular'
      - run: cd apps/
      - run: npm i --production=false
      - run: npm run test-angular-fe
  build-alpha_be-job:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run: npm install
      - run: node_modules/.bin/nx test alpha-be
      - run: node_modules/.bin/nx build alpha-be
      - run: pwd && ls
      - eb/setup


workflows:
  testbuildwf:
    when: << pipeline.parameters.build-test >>
    jobs:
      - build-test-job
  angularbuildwf:
    when: << pipeline.parameters.build-angular_fe >>
    jobs:
      - build-angular-job
  alpha-be-wf:
    when: << pipeline.parameters.build-alpha_be >>
    jobs:
      - build-alpha_be-job


