version: 2.1

parameters:
  build-angular_fe:
    type: boolean
    default: false
  build-test:
    type:  boolean
    default: false

jobs:
  build-test-job:
    docker:
      - image: alpine:3.15
    steps:
      - run: echo 'Building Test'
  build-angular-job:
    docker:
      - image: alpine:3.15
    steps:
      - run: echo 'Building angular'

workflows:
  testbuildwf:
    when: << pipeline.parameters.build-test >>
    jobs:
      - build-test-job
  angularbuildwf:
    when: << pipeline.parameters.build-angular_fe >>
    jobs:
      - build-angular-job
